Repository corona-warn-app/cwa-server, pull requests merged in 2020-05, with the labels that each got.

#252 Update SECURITY.md
  SECURITY.md
Labels: in review

#239 DiagnosisKey: Reject negative retention period for threshold calculation
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKey.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyTest.java
Labels: community

#215 remove WORKDIR from Docker build stage
  services/distribution/Dockerfile
  services/submission/Dockerfile
Labels: community

#238 #183: Use configuration classes instead of `@value` annotations
  services/distribution/pom.xml
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/Application.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/appconfig/structure/directory/AppConfigurationDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/appconfig/structure/directory/decorator/AppConfigurationSigningDecorator.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/component/AppConfigurationStructureProvider.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/component/CryptoProvider.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/component/CwaApiStructureProvider.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/component/DiagnosisKeysStructureProvider.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/component/OutputDirectoryProvider.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysCountryDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDateDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysHourDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/decorator/DateAggregatingDecorator.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/decorator/DiagnosisKeySigningDecorator.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/file/TemporaryExposureKeyExportFile.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/archive/ArchiveOnDisk.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/archive/decorator/signing/AbstractSigningDecorator.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/archive/decorator/signing/SigningDecoratorOnDisk.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/directory/decorator/indexing/AbstractIndexingDecorator.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/directory/decorator/indexing/IndexingDecoratorOnDisk.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/config/DistributionServiceConfig.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/ObjectStoreAccess.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/ObjectStoreConfigurationProperties.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/RetentionPolicy.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/TestDataGeneration.java
  services/distribution/src/main/resources/application-cloud.properties
  services/distribution/src/main/resources/application.properties
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/component/CryptoProviderTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDirectoryTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/structure/archive/decorator/signing/SigningDecoratorTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/structure/directory/decorators/indexing/IndexingDecoratorTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/config/DistributionServiceConfigTest.java
  services/distribution/src/test/resources/application.properties
  services/submission/src/main/java/app/coronawarn/server/services/submission/ServerApplication.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/config/SubmissionServiceConfig.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/controller/SubmissionController.java
  services/submission/src/main/resources/application-config-test.properties
  services/submission/src/test/java/app/coronawarn/server/services/submission/config/SubmissionServiceConfigTest.java
Labels: community

#291 add project URLs to POM file
  pom.xml
Labels: community

#293 Only throw exception, don't log (#270)
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/component/CryptoProvider.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/io/IO.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/archive/decorator/signing/AbstractSigningDecorator.java
Labels: community

#285 Fix/docker compose limitation #255
  THIRD-PARTY-NOTICES
  docker-compose.yml
  scripts/wait-for-it/README.md
  scripts/wait-for-it/wait-for-it.sh
Labels: community

#256 DiagnosisKey: Change type long to int for rolling period and rolling start number
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKey.java
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyBuilder.java
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyBuilders.java
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/validation/ValidRollingStartIntervalNumber.java
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/validation/ValidRollingStartIntervalNumberValidator.java
  common/persistence/src/main/resources/db/migration/h2/V2__changeTypeToIntForRollingNumbers.sql
  common/persistence/src/main/resources/db/migration/postgres/V2__changeTypeToIntForRollingNumbers.sql
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyBuilderTest.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyServiceMockedRepositoryTest.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyTest.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/service/DiagnosisKeyServiceTest.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/service/DiagnosisKeyServiceTestHelper.java
  docs/architecture-overview.md
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/file/TemporaryExposureKeyExportFile.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/TestDataGeneration.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/common/Helpers.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/SubmissionControllerTest.java
Labels: community

#274 Commiting changes for the following sonarcloud issues.
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/appconfig/structure/directory/AppConfigurationDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysCountryDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDateDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/decorator/DateAggregatingDecorator.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/util/DateTime.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/archive/ArchiveOnDisk.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/file/FileOnDisk.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/TestDataGeneration.java
Labels: community

#317 Refined Submission Instructions in SECURITY.md
  SECURITY.md
Labels: in review

#299 Adjust Risk Score Parameters (#298)
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/appconfig/validation/ExposureConfigurationValidator.java
  services/distribution/src/main/resources/master-config/exposure-config.yaml
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/appconfig/validation/ExposureConfigurationValidatorTest.java
  services/distribution/src/test/resources/parameters/score_negative.yaml
Labels: community

#309 use markdownlint to assure MD file consistency
  .github/workflows/markdown-analysis.yml
  codestyle/.markdownlint.yml
Labels: community, in review

#310 fix issues in markdown files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/architecture-overview.md
Labels: community, in review

#296 Ensure StopWatch is stopped
  services/submission/src/main/java/app/coronawarn/server/services/submission/controller/SubmissionController.java
Labels: community

#303 reduce version definitions in POMs (rework)
  .gitignore
  .mvn/maven.config
  THIRD-PARTY-NOTICES
  common/persistence/pom.xml
  common/pom.xml
  common/protocols/pom.xml
  pom.xml
  services/distribution/pom.xml
  services/pom.xml
  services/submission/pom.xml
Labels: community

#307 Crypto provider load resources on startup (#306)
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/component/CryptoProvider.java
Labels: community, in review

#321 Fixed additional sonar issues
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/appconfig/structure/directory/AppConfigurationDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysCountryDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDateDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/file/TemporaryExposureKeyExportFile.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/util/DateTime.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/archive/ArchiveOnDisk.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/file/FileOnDisk.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/config/DistributionServiceConfig.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/verification/TanVerifier.java
Labels: in review

#352 Removes use of obsolete java.util.Stack
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/directory/IndexDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/directory/IndexDirectoryOnDisk.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/util/ImmutableStack.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/structure/util/ImmutableStackTest.java
Labels: community, in review

#371 Decouple ObjectStoreAccess from specific client
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/ObjectStoreAccess.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/S3Publisher.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/S3RetentionPolicy.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/client/MinioClientWrapper.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/client/ObjectStoreClient.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/client/ObjectStoreClientConfig.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/client/ObjectStoreOperationFailedException.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/client/S3Object.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/publish/PublishedFileSet.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/S3Distribution.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/ObjectStoreAccessTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/ObjectStoreAccessUnitTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/S3PublisherIntegrationTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/S3PublisherTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/S3RetentionPolicyTest.java
Labels: enhancement

#362 add license-plugin configuration for file headers
  .mvn/maven.config
  common/persistence/pom.xml
  pom.xml
  services/pom.xml
Labels: community, in review

#358 Create pull_request_template.md
  .github/pull_request_template.md
Labels: in review
