Repository corona-warn-app/cwa-server, pull requests merged in 2020-06, with the labels that each got.

#375 Prepare dpkg metadata for Clair image scan
  scripts/DpkgHelper.java
  services/distribution/Dockerfile
  services/submission/Dockerfile
Labels: in review

#387 Improve external tan verification
  THIRD-PARTY-NOTICES
  services/submission/pom.xml
  services/submission/src/main/java/app/coronawarn/server/services/submission/ServerApplication.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/verification/Tan.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/verification/TanVerifier.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/verification/VerificationServerClient.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/verification/FeignTestConfiguration.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/verification/TanTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/verification/TanVerifierTest.java
  services/submission/src/test/resources/application.yaml
Labels: community

#409 Fixing S3ClientWrapper's bucketExists method
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/ObjectStoreAccess.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/client/S3ClientWrapper.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/client/S3ClientWrapperTest.java
Labels: community, in review

#429 Removed explicit Autowired annotations (closes #404)
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/service/DiagnosisKeyService.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/component/DiagnosisKeysStructureProvider.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/S3RetentionPolicy.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/controller/SubmissionController.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/verification/TanVerifier.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/RequestExecutor.java
Labels: community, in review

#447 Update documentation
  docs/architecture-overview.md
Labels: documentation

#467 [trivial] Fix postgres endpoint in README
  README.md
Labels: community

#469 Documentation: Fix broken link in architecture-overview.md
  docs/architecture-overview.md
Labels: community

#478 Number of bytes should not depend on Locale
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyBuilderTest.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyServiceMockedRepositoryTest.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyTest.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/directory/decorator/indexing/IndexingDecoratorOnDisk.java
Labels: community, in review

#481 Fix grep command
  scripts/wait-for-it/wait-for-it.sh
Labels: community, in review

#471 replace size-comparison in test with "hasSameSizeAs"
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/service/DiagnosisKeyServiceTestHelper.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/SubmissionControllerTest.java
Labels: community, in review

#488 Consistently use UTC for LocalDateTime
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/component/DiagnosisKeysStructureProvider.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/TestDataGeneration.java
Labels: community

#494 docs for running maven build with services from docker-compose
  README.md
Labels: community, in review

#555 rename package 'decorators' to 'decorator' (issue #545)
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/structure/directory/decorator/DirectoryDecoratorTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/structure/directory/decorator/indexing/IndexingDecoratorTest.java
Labels: community

#554 Declutter SubmissionController
  services/submission/src/main/java/app/coronawarn/server/services/submission/config/SubmissionServiceConfig.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/controller/FakeDelayManager.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/controller/FakeRequestController.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/controller/SubmissionController.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/monitoring/SubmissionMonitor.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/FakeDelayManagerTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/FakeRequestControllerTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/PayloadValidationTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/RequestExecutor.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/SubmissionControllerTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/monitoring/SubmissionMonitorTest.java
Labels: submission service

#599 Add missing blanks in warn messages
  services/submission/src/main/java/app/coronawarn/server/services/submission/ServerApplication.java
Labels: community

#575 Minor code quality improvements
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/appconfig/structure/directory/AppConfigurationDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/appconfig/validation/ApplicationConfigurationValidator.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/appconfig/validation/RiskScoreClassificationValidator.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/appconfig/validation/RiskScoreValidator.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/component/CwaApiStructureProvider.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysCountryDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDateDirectory.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/TestDataGeneration.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/appconfig/validation/ApplicationConfigurationValidatorTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/structure/directory/IndexDirectoryTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/structure/directory/decorator/indexing/IndexingDecoratorTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/common/Helpers.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/S3PublisherTest.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/monitoring/SubmissionMonitor.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/monitoring/BatchCounterTest.java
Labels: community

#625 OSP is OpenStack Platform, OpenShift is OCP
  docs/ARCHITECTURE.md
Labels: community, in review
