Repository corona-warn-app/cwa-server, pull requests merged in 2020-10, with the labels that each got.

#833 Validation for keys downloaded from EFGS
  services/download/src/main/java/app/coronawarn/server/services/download/FederationBatchProcessor.java
  services/download/src/main/java/app/coronawarn/server/services/download/validation/ValidFederationKeyFilter.java
  services/download/src/test/java/app/coronawarn/server/services/download/FederationBatchProcessorTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/FederationBatchTestHelper.java
  services/download/src/test/java/app/coronawarn/server/services/download/normalization/FederationKeyNormalizerTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/validation/ValidFederationKeyFilterTest.java
Labels: federation

#850 Change submission validations
  services/submission/src/main/java/app/coronawarn/server/services/submission/validation/ValidSubmissionPayload.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/PayloadValidationTest.java
Labels: federation

#843 Feature/federation download filtering
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/FederationBatchStatus.java
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/service/common/ValidDiagnosisKeyFilter.java
  services/callback/src/test/java/app/coronawarn/server/services/callback/controller/CallbackControllerTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/integration/ObjectStoreAccessIT.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/integration/S3PublisherIT.java
  services/download/src/main/java/app/coronawarn/server/services/download/DownloadServiceConfig.java
  services/download/src/main/java/app/coronawarn/server/services/download/FederationBatchProcessor.java
  services/download/src/main/java/app/coronawarn/server/services/download/validation/ValidFederationKeyFilter.java
  services/download/src/main/resources/application.yaml
  services/download/src/test/java/app/coronawarn/server/services/download/DownloadIntegrationTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/FederationBatchProcessorTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/FederationBatchTestHelper.java
  services/download/src/test/java/app/coronawarn/server/services/download/normalization/FederationKeyNormalizerTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/validation/ValidFederationKeyFilterTest.java
  services/download/src/test/resources/application.yaml
  services/submission/src/test/java/app/coronawarn/server/services/submission/ServerApplicationTests.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/config/SubmissionServiceConfigValidatorTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/FakeRequestControllerTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/PayloadValidationTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/SubmissionControllerTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/integration/SubmissionPersistenceIT.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/monitoring/VerificationServiceHealthIndicatorTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/verification/TanVerifierTest.java
  services/upload/src/test/java/app/coronawarn/server/services/federation/upload/integration/UploadKeyIT.java
  services/upload/src/test/java/app/coronawarn/server/services/federation/upload/runner/UploadTest.java
Labels: federation

#842 Validate downloadserviceconfig
  services/download/src/main/java/app/coronawarn/server/services/download/Application.java
  services/download/src/main/java/app/coronawarn/server/services/download/FederationBatchProcessor.java
  services/download/src/main/java/app/coronawarn/server/services/download/config/DownloadServiceConfig.java
  services/download/src/main/java/app/coronawarn/server/services/download/config/DownloadServiceConfigValidator.java
  services/download/src/main/java/app/coronawarn/server/services/download/normalization/FederationKeyNormalizer.java
  services/download/src/main/java/app/coronawarn/server/services/download/runner/Download.java
  services/download/src/main/java/app/coronawarn/server/services/download/runner/RetentionPolicy.java
  services/download/src/main/java/app/coronawarn/server/services/download/validation/ValidFederationKeyFilter.java
  services/download/src/main/resources/application.yaml
  services/download/src/test/java/app/coronawarn/server/services/download/DownloadIntegrationEmptyResponseTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/DownloadIntegrationTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/FederationBatchProcessorTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/FederationBatchTestHelper.java
  services/download/src/test/java/app/coronawarn/server/services/download/config/DownloadServiceConfigValidatorTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/normalization/FederationKeyNormalizerTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/runner/DownloadTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/runner/RetentionPolicyTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/validation/ValidFederationKeyFilterTest.java
Labels: federation

#863 Document data migration and Flyway
  docs/PERSISTENCE.md
Labels: documentation

#864 Refinement of TRL/DSOS derivation maps
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/config/TekFieldDerivations.java
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/config/YamlPropertySourceFactory.java
  common/persistence/src/main/resources/derivation-maps.yaml
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/TestApplication.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/domain/config/TekFieldDerivationsTest.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/domain/config/YamlPropertySourceFactoryTest.java
  services/download/src/main/java/app/coronawarn/server/services/download/config/DownloadServiceConfig.java
  services/download/src/main/java/app/coronawarn/server/services/download/config/DownloadServiceConfigValidator.java
  services/download/src/main/java/app/coronawarn/server/services/download/normalization/FederationKeyNormalizer.java
  services/download/src/main/resources/application.yaml
  services/download/src/test/java/app/coronawarn/server/services/download/FederationBatchProcessorTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/config/DownloadServiceConfigValidatorTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/normalization/FederationKeyNormalizerTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/runner/RetentionPolicyTest.java
  services/download/src/test/resources/application.yaml
  services/submission/src/main/java/app/coronawarn/server/services/submission/config/SubmissionServiceConfig.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/config/SubmissionServiceConfigValidator.java
  services/submission/src/main/java/app/coronawarn/server/services/submission/normalization/SubmissionKeyNormalizer.java
  services/submission/src/main/resources/application.yaml
  services/submission/src/test/java/app/coronawarn/server/services/submission/config/SubmissionServiceConfigValidatorTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/PayloadValidationTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/SubmissionControllerTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/normalization/SubmissionKeyNormalizerTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/verification/TanVerifierTest.java
  services/submission/src/test/resources/application.yaml
Labels: federation

#862 Update documentation for submission
  docs/README.md
  docs/SUBMISSION.md
  services/submission/src/main/java/app/coronawarn/server/services/submission/validation/ValidSubmissionPayload.java
Labels: federation

#857 Docu for Download Service
  docs/DOWNLOAD.md
  docs/README.md
Labels: documentation

#861 Docs/federation
  docs/ARCHITECTURE.md
  docs/DISTRIBUTION.md
  docs/DOWNLOAD.md
  docs/FEDERATION-CALLBACK.md
  docs/FEDERATION-DOWNLOAD.md
  docs/FEDERATION-UPLOAD.md
  docs/README.md
  docs/SUBMISSION.md
  docs/images/callback-flow.png
Labels: documentation

#898 Introduce new paramter that allows to enforce downloading batches for…
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/repository/FederationBatchInfoRepository.java
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/service/FederationBatchInfoService.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/repository/FederationBatchInfoRepositoryTest.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/service/FederationBatchInfoServiceTest.java
  services/download/src/main/java/app/coronawarn/server/services/download/FederationBatchProcessor.java
  services/download/src/main/java/app/coronawarn/server/services/download/config/DownloadServiceConfig.java
  services/download/src/main/java/app/coronawarn/server/services/download/runner/Download.java
  services/download/src/main/resources/application.yaml
  services/download/src/test/java/app/coronawarn/server/services/download/DownloadEnforceDownloadAgainIntegrationTest.java
  services/download/src/test/java/app/coronawarn/server/services/download/FederationBatchProcessorTest.java
  services/download/src/test/resources/application-federation-enforce-download-again-integration.yaml
  services/download/src/test/resources/application.yaml
  services/download/src/test/resources/db/testdata-enforce-download-again/V99__createTestDataForDownloadTodayAgainIntegrationTest.sql
Labels: federation

#884 Document EUR package
  docs/DISTRIBUTION.md
Labels: documentation

#870 Distribution Service Documentation
  docs/DISTRIBUTION.md
Labels: distribution service, documentation

#830 Refactoring/reformatting in tests
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/appconfig/validation/ApplicationConfigurationValidatorTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/appconfig/validation/ExposureConfigurationValidatorTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDirectoryTest.java
Labels: community

#946 Dep/updates
  .mvn/maven-version-rules.xml
  pom.xml
  services/submission/pom.xml
  services/upload/pom.xml
Labels: enhancement
