Repository corona-warn-app/cwa-server, pull requests merged in 2020-07, with the labels that each got.

#574 switch to spring-2.3.1
  common/persistence/pom.xml
  services/pom.xml
Labels: community, in review

#194 Use maven wrapper as the single source of truth for maven version in the project
  .circleci/config.yml
  .gitattributes
  .github/workflows/codeql-analysis.yml
  docker-compose-it.yaml
  services/distribution/Dockerfile
  services/submission/Dockerfile
Labels: community, in review

#647 downscale gracefully
  services/submission/src/main/java/app/coronawarn/server/services/submission/ServerApplication.java
  services/submission/src/main/resources/application.yaml
Labels: ibso, submission service

#651 Make .env config advice more explicit
  README.md
Labels: community

#664 Enhancement/time zone handling
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/component/DiagnosisKeysStructureProvider.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/decorator/DateIndexingDecorator.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/decorator/HourIndexingDecorator.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/util/TimeUtils.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/S3RetentionPolicy.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/TestDataGeneration.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/component/DiagnosisKeysStructureProviderTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysHourDirectoryTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/decorator/HourIndexingDecoratorTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/structure/util/TimeUtilsTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/S3RetentionPolicyTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/runner/TestDataGenerationTest.java
Labels: distribution service, enhancement

#666 Refactored header generation for testing
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/FakeRequestControllerTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/HttpHeaderBuilder.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/PayloadValidationTest.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/RequestExecutor.java
  services/submission/src/test/java/app/coronawarn/server/services/submission/controller/SubmissionControllerTest.java
Labels: community, in review

#687 Feature/federation distribution service
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKey.java
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyBuilder.java
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyBuilders.java
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/repository/DiagnosisKeyRepository.java
  common/persistence/src/main/java/app/coronawarn/server/common/persistence/service/DiagnosisKeyService.java
  common/persistence/src/main/resources/db/migration/V5__addCountryColumn.sql
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyServiceMockedRepositoryTest.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/domain/DiagnosisKeyTest.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/service/DiagnosisKeyServiceTest.java
  common/persistence/src/test/java/app/coronawarn/server/common/persistence/service/DiagnosisKeyServiceTestHelper.java
  services/callback/pom.xml
  services/callback/src/main/resources/application.yaml
  services/callback/src/test/resources/application.yaml
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/config/DistributionServiceConfig.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/RetentionPolicy.java
  services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/TestDataGeneration.java
  services/distribution/src/main/resources/application.yaml
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/common/Helpers.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/runner/RetentionPolicyRunnerTest.java
  services/distribution/src/test/java/app/coronawarn/server/services/distribution/runner/TestDataGenerationTest.java
Labels: federation, ibso
